### ISSUE TITLE
Update action will replace every entry with nil if entered as written in readme

### ISSUE THREAD

**Issue by rcrdlbl** [learn-co-curriculum/rails-edit-update-action-readme#23]
The params hash from the edit form passes params through as `params[:article][:title]`
Therefore using:
```ruby
def update
  @article = Article.find(params[:id])
  @article.update(title: params[:title], description: params[:description])
  redirect_to article_path(@article)
end
```
replaces everything in the article with nil

Should probably replace it with something like:

```ruby
def update
  @article = Article.find(params[:id])
  @article.update(params[:article])
  redirect_to article_path(@article)
end
```

or

```ruby
def update
  @article = Article.find(params[:id])
  @article.update(title: params[:article][:title], description: params[:article][:description])
  redirect_to article_path(@article)
end
```

**Comment by krystlebarnes** [comment]
Commenting to confirm the curriculum still needs to be updated to explain this. The spec tests were fixed to account for the nested params with form_for, but the curriculum still needs to be updated to account for the nested params in regards to the update method in the ArticlesController, as @rcrdlbl explained.

**Comment by maxwellbenton** [comment]
HI @rcrdlbl and @krystlebarnes,

Thank you for providing this feedback. We've updated this content's instructions, tests and solution so that they are aligned and that the provided code snippets pass all tests and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
