### ISSUE TITLE
params for edit form_for are incorrect

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/rails-edit-update-action-readme#27]
The params.inspect screenshot shows the params coming back from the form_for(@post) coming back as `{title: "title", description: "description"}`, but form_for automatically nests attributes, so it should be `{ post: {title: "title", description: "description"} }`. This also means the update should be `@post.update(title: params[:post][:title], description: params[:post][:description])`.

**Comment by ioreka** [comment]
Params still not correct, also update still needs reviewing to:

 @article.update(title: params[:title], description: params[:description])

:)

**Comment by helloamandamurphy** [comment]
Params are still not correct. This is the correct code for the update method:
```
def update
    @article = Article.find(params[:id])
    @article.update(title: params[:article][:title], description: params[:article][:description])
    @article.save
    redirect_to article_path(@article)
  end
```
Also, with the introduction of `form_for` there needs to be an explanation that the params are automatically nested.

These Rails ReadMe's need a serious facelift. I'm not learning due to the poor instruction and the code that is provided to copy and paste to follow along--80% of the time it fails the tests. It's wasting my time.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
