### ISSUE TITLE
Update action does not work

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/rails-edit-update-action-readme#30]
The update action as shown in the lab does not work. 

Instead of:
```
@article.update(title: params[:title], description: params[:description])
```
it should be:
```
@article.update(title: params[:article][:title], description: params[:article][:description])
```

**Comment by meg-gutshall** [comment]
This issue has not been solved yet. Many issues and PRs with perfectly good fixes provided by Flatiron students are still sitting untouched weeks later and it's frustrating as a student who just spent a lot of time working on this lab to come to the repo and see that's there's a known issue that just hasn't been fixed yet. This is something I've brought up multiple times with instructors and they say that the curriculum team is busy with other updates. I don't know what else to do to get people's attention so I found Flatiron curriculum employees on LinkedIn in hopes that they will **_do something_** about this persistent problem. @maxwellbenton @sgharms @jenmyers @aviflombaum @jmburges

**Comment by maxwellbenton** [comment]
Hi @aburk3,

Thank you for spotting this and providing feedback. We have updated this lesson's content so that the code snippet correctly uses nested params, passes the final test when used and believe this issue has been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
