### ISSUE TITLE
The final entry in update doesn't pass the tests.

### ISSUE THREAD

**Issue by jbharwood** [learn-co-curriculum/rails-edit-update-action-readme#31]
def update
  @article = Article.find(params[:id])
  @article.update(title: params[:title], description: params[:description])
  redirect_to article_path(@article)
end

**Comment by JoeQuattrone** [comment]
Same for me

**Comment by schanrai** [comment]
me too

**Comment by maxwellbenton** [comment]
Hi @jbharwood, @JoeQuattrone, and @schanrai,

Thank you for spotting this and providing feedback. We have updated this lesson's content so that the code snippet correctly uses nested params, passes the final test when used and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
