### ISSUE TITLE
The update method has you enter description: params[:description] but it needs to be description: params[:article][:description] to pass the final test. Same with the title 

### ISSUE THREAD

**Issue by kmoosman** [learn-co-curriculum/rails-edit-update-action-readme#32]
The lesson has the update method as: 

def update
  @article = Article.find(params[:id])
  @article.update(title: params[:title], description: params[:description])
  redirect_to article_path(@article)
end

but it nees to be: 
def update
    @article = Article.find(params[:id])
    @article.update(title: params[:article][:title], description: params[:article][:description])
    redirect_to article_path(@article)
  end

in order to pass the final test

**Comment by maxwellbenton** [comment]
Hi @kmoosman,

Thank you for spotting this and providing feedback. We have updated this lesson's content so that the code snippet correctly uses nested params, passes the final test when used and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
