### ISSUE TITLE
The update action is wrong

### ISSUE THREAD

**Issue by MaxBrooks114** [learn-co-curriculum/rails-edit-update-action-readme#33]
The update action only works with a nested params hash i.e. params[:article][:title] instead of just params[:title]. As this is only a lesson and not a lab, this is wrong.

**Comment by maxwellbenton** [comment]
Hi @MaxBrooks114,

Thank you for spotting this and providing feedback. We have updated this lesson's content to so that the code snippet correctly uses nested params and passes the final test when used and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by MaxBrooks114** [comment]
It was my pleasure. Honestly, it’s good that I can identify an error. Means I am understanding the material. Thanks for correcting!
